# AndroidX & Jetpack Compose Prerequisite
android.useAndroidX=true

# JVM Heap, Metaspace & Garbage Collection tuning for R8/ProGuard Release Minification
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC

# Parallel compilation & configuration caching for build pipeline speed
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Code style alignment
kotlin.code.style=official
