name: Generate Permanent Keystore

on:
  workflow_dispatch:
    inputs:
      store_password:
        description: 'Choose a strong Keystore Password'
        required: true
        default: 'MelovishKeyPass2026'
      key_password:
        description: 'Choose a strong Key Password (often same as store password)'
        required: true
        default: 'MelovishKeyPass2026'
      key_alias:
        description: 'Alias Name'
        required: true
        default: 'melovish_key'

jobs:
  create-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore via Keytool
        run: |
          keytool -genkeypair \
            -v \
            -keystore melovish-release-key.jks \
            -alias "${{ github.event.inputs.key_alias }}" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "${{ github.event.inputs.store_password }}" \
            -keypass "${{ github.event.inputs.key_password }}" \
            -dname "CN=Melovish, OU=Mobile, O=Melovish Music, L=City, ST=State, C=IN"

      - name: Print Base64 String to Execution Log
        run: |
          echo "====================== BASE64 KEYSTORE START ======================"
          base64 -w 0 melovish-release-key.jks
          echo ""
          echo "======================= BASE64 KEYSTORE END ======================="

      - name: Upload Keystore Artifact for Safe Backup
        uses: actions/upload-artifact@v4
        with:
          name: melovish-release-keystore
          path: melovish-release-key.jks
          retention-days: 5
